//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFeedsDomain.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbFeedsEntities : DbContext
    {
        public dbFeedsEntities()
            : base("name=dbFeedsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FeedsProvider> FeedsProviders { get; set; }
        public virtual DbSet<FeedType> FeedTypes { get; set; }
        public virtual DbSet<ProviderMainPage> ProviderMainPages { get; set; }
    }
}
