//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFeedsDomain.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedType
    {
        public FeedType()
        {
            this.FeedsProviders = new HashSet<FeedsProvider>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<FeedsProvider> FeedsProviders { get; set; }
    }
}
