//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFeedsDomain.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedsProvider
    {
        public FeedsProvider()
        {
            this.ProviderMainPages = new HashSet<ProviderMainPage>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int FeedsType { get; set; }
        public string Url { get; set; }
    
        public virtual FeedType FeedType { get; set; }
        public virtual ICollection<ProviderMainPage> ProviderMainPages { get; set; }
    }
}
