//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFeedsDomain.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProviderMainPage
    {
        public string ImageUrl { get; set; }
        public int FeedsProviderID { get; set; }
        public int WeekDay { get; set; }
        public Nullable<int> MainPageParserType { get; set; }
    
        public virtual FeedsProvider FeedsProvider { get; set; }
    }
}
